services:
  nginx:
    image: nginx
    ports:
      - 8080:80
  
  giropops-senhas:
    image: lpampolha/linuxtips-giropops-senhas:5.0
    ports: 
      - "5000:5000"
    environment:
      REDIS_HOST: redis
    networks:
      - strigus
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - strigus    
networks:
  strigus:
    driver: bridge